### ISSUE TITLE
不知道为什么一直崩溃在这里哦

### ISSUE THREAD

**Issue by ccchina** [baozoudiudiu/CWCarousel#15]
- (NSInteger)numbers {
    if(self.datasource &&
       [self.datasource respondsToSelector:@selector(numbersForCarousel)]) {
        self.pageControl.numberOfPages = [self.datasource numbersForCarousel];
        return self.pageControl.numberOfPages;
    }
    return 0;
}

**Comment by JonKerr-China** [comment]
我也遇到同样问题。很容易在这个地方闪退。

**Comment by lovelyNewYear** [comment]
这个问题有没被解决
