### ISSUE TITLE
更新1.1.5后 崩溃日志还是这个样子，麻烦有时间看一下

### ISSUE THREAD

**Issue by lovelyNewYear** [baozoudiudiu/CWCarousel#21]
bugly的崩溃日志 每次最多的问题就是这个，麻烦有时间解答一下 这个是不是闪退？
![WX20200525-093513](https://user-images.githubusercontent.com/13994302/82770524-76cc2100-9e6b-11ea-9e8a-d96a60d49fef.png)

**Comment by ThisIszas** [comment]
在使用这个组件的 dealloc里把组件的delegate 和 datasource 都置为 nil.

比如我这就是:
`- (void)dealloc{ 
    self.xxxCarousel.delegate = nil;
    self.xxxCarousel.datasource = nil;
}`
