### ISSUE TITLE
能不能增加一种样式

### ISSUE THREAD

**Issue by vitasapple** [baozoudiudiu/CWCarousel#22]
目前第三种样式是中间图片放大，它的左边显示的是左边那张图片的右侧，它的右边显示的是右边那张图片的左侧，能加一种样式，就是左边显示的是左边图片的最左侧，右边显示的是右边图片的最右侧，就类似一种堆叠的效果

**Comment by DongfengWang123** [comment]
> 目前第三种样式是中间图片放大，它的左边显示的是左边那张图片的右侧，它的右边显示的是右边那张图片的左侧，能加一种样式，就是左边显示的是左边图片的最左侧，右边显示的是右边图片的最右侧，就类似一种堆叠的效果

===>你写出来或者找到类似的demo了吗?我现在也需要这种效果.麻烦分享一下呗

**Comment by vitasapple** [comment]
> > 目前第三种样式是中间图片放大，它的左边显示的是左边那张图片的右侧，它的右边显示的是右边那张图片的左侧，能加一种样式，就是左边显示的是左边图片的最左侧，右边显示的是右边图片的最右侧，就类似一种堆叠的效果
> 
> ===>你写出来或者找到类似的demo了吗?我现在也需要这种效果.麻烦分享一下呗

我已经解决了。你还要吗，加我qq529254622我发你demo

**Comment by baozoudiudiu** [comment]
1.1.8版本可以通过设置间距为负数实现
