### ISSUE TITLE
iOS 14 在非无限滚动模式时，头尾两张图片拖动后不会自动弹回

### ISSUE THREAD

**Issue by inrtgdje** [baozoudiudiu/CWCarousel#32]
使用demo里的swift版本在iOS 14的模拟器上使用禁止无限滚动，正常模式时，首张图片往右拖动时会停在拖动的地方，最后一张图片往左拖动后会停在拖动的地方。都不会回弹到正常显示的位置。屏幕录制压缩视频已上传了。
[屏幕录制2020-11-26 20.31.16.zip](https://github.com/baozoudiudiu/CWCarousel/files/5603037/2020-11-26.20.31.16.zip)

**Comment by inrtgdje** [comment]
![image](https://user-images.githubusercontent.com/17985614/100356920-e4315800-302e-11eb-8f8c-644190e74277.png)
在iOS 14时添加了滚动代码
if #available(iOS 14.0, *) {
                    self.scrollToIndexPathAnimated(self.currentIndexPath)
                }

**Comment by baozoudiudiu** [comment]
👍
