### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by fengshuo1992** [baozoudiudiu/CWCarousel#33]
-[CWCarousel numbers] (CWCarousel.m:)  崩溃

**Comment by fengshuo1992** [comment]
Foundation | __NSFireDelayedPerform + 416
-- | --
4 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
5 CoreFoundation | ___CFRunLoopDoTimer + 1064
6 CoreFoundation | ___CFRunLoopDoTimers + 328
7 CoreFoundation | ___CFRunLoopRun + 1936
8 CoreFoundation | CFRunLoopRunSpecific + 600
9 GraphicsServices | GSEventRunModal + 164
10 UIKitCore | -[UIApplication _run] + 1072
11 UIKitCore | UIApplicationMain + 168

OC 版本 崩溃率还挺高的 在bugly 收集的  目前还在看崩溃路径

**Comment by baozoudiudiu** [comment]
提交了一个版本， cocoaPods还没更新， 请直接引入使用工程里的文件。
建议使用swift版本， 后期OC版本可能决定放弃维护了。

**Comment by syp1027825441** [comment]
> Foundation	__NSFireDelayedPerform + 416
> 4 CoreFoundation	_**CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION** + 32
> 5 CoreFoundation	___CFRunLoopDoTimer + 1064
> 6 CoreFoundation	___CFRunLoopDoTimers + 328
> 7 CoreFoundation	___CFRunLoopRun + 1936
> 8 CoreFoundation	CFRunLoopRunSpecific + 600
> 9 GraphicsServices	GSEventRunModal + 164
> 10 UIKitCore	-[UIApplication _run] + 1072
> 11 UIKitCore	UIApplicationMain + 168
> OC 版本 崩溃率还挺高的 在bugly 收集的 目前还在看崩溃路径

终极解决方案是把定时任务改成NSTimer，看我发的问题里有代码
