### ISSUE TITLE
在第三个样式中怎么让中间cell始终在左右两个cell之上层叠显示?

### ISSUE THREAD

**Issue by Spaino** [baozoudiudiu/CWCarousel#4]
您好!实现代码很轻巧,非常不错,加油!
有一个问题:
在第三个样式中调整self.factItemSpace = -30;
怎么让中间cell始终在左右两个cell之上层叠显示?

**Comment by baozoudiudiu** [comment]
您好,所有的属性在.h文件中都有注释,您说的那种效果,第三种样式默认就是中间cell上层显示的.不太明白你说的问题
