### ISSUE TITLE
能不能取消循环滚动呢？

### ISSUE THREAD

**Issue by Jiangfy** [baozoudiudiu/CWCarousel#5]

**Comment by baozoudiudiu** [comment]
你的意思是指滑到第一张或者最后一张就不自动衔接了是么?
如果是这样的话,是不支持的,你可能需要改下源码

**Comment by ymsying** [comment]
如果只有一张图片，如何设置成只显示一张而不重复出现相同的内容呢？

**Comment by baozoudiudiu** [comment]
抱歉! 
1.因为某些样式有前后2张预览效果,所以暂时没有考虑只有一张图片的情况.
2.项目中获取到数据后,判断一下,只有一张的话直接用UIImageView加载就好了,多张图片的情况再考虑加载轮播图.
3.感谢反馈,后期版本可能会考虑将这种情况加载到轮播图中
4.其实我写这个轮播图的初衷,耦合度并不高,封装度也没有特别高.目的就是方便使用者可以高度自定义,根据自己项目中的需求进行二次封装.
